//! Static demo projections for left-sidebar interface scaffolding.

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum AtomShelf {
    Pinned,
    Active,
    Settled,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum AtomStatus {
    Working,
    Monitoring,
    Approval,
    Input,
    Failed,
    Ready,
    Woke,
}

impl AtomStatus {
    pub fn label(self) -> Option<&'static str> {
        match self {
            Self::Working => Some("Working"),
            Self::Monitoring => Some("Monitoring"),
            Self::Approval => Some("Approval"),
            Self::Input => Some("Input"),
            Self::Failed => Some("Failed"),
            Self::Woke => Some("Woke"),
            Self::Ready => None,
        }
    }
}

#[derive(Clone, Debug)]
pub struct DemoProject {
    pub key: &'static str,
    pub display_name: &'static str,
    pub favicon_hue: u32,
}

#[derive(Clone, Debug)]
pub struct DemoDraft {
    pub id: &'static str,
    pub project_key: &'static str,
    pub project_title: &'static str,
    pub preview: &'static str,
}

#[derive(Clone, Debug)]
pub struct DemoAtom {
    pub id: &'static str,
    pub title: &'static str,
    pub project_key: &'static str,
    pub project_title: &'static str,
    pub branch: Option<&'static str>,
    pub shelf: AtomShelf,
    pub time_label: &'static str,
    pub status: AtomStatus,
    pub pr_number: Option<u32>,
    pub diff_insertions: Option<u32>,
    pub diff_deletions: Option<u32>,
    pub is_unread: bool,
    pub is_woke: bool,
    pub terminal_process_count: u32,
}

pub const ALL_ATOMS_LABEL: &str = "All atoms";

pub const DEMO_PROJECTS: [DemoProject; 2] = [
    DemoProject {
        key: "opencore",
        display_name: "opencore_rustroops",
        favicon_hue: 0xD7_19_21,
    },
    DemoProject {
        key: "sample_app",
        display_name: "sample_app",
        favicon_hue: 0x3B_82_F6,
    },
];

pub const DEMO_DRAFT: DemoDraft = DemoDraft {
    id: "draft-1",
    project_key: "opencore",
    project_title: "opencore_rustroops",
    preview: "New atom draft…",
};

pub const DEMO_ATOMS: [DemoAtom; 15] = [
    DemoAtom {
        id: "pinned-1",
        title: "Fix dock layout persistence",
        project_key: "opencore",
        project_title: "opencore_rustroops",
        branch: Some("feat/shell-dock"),
        shelf: AtomShelf::Pinned,
        time_label: "2h",
        status: AtomStatus::Working,
        pr_number: Some(42),
        diff_insertions: Some(128),
        diff_deletions: Some(24),
        is_unread: false,
        is_woke: false,
        terminal_process_count: 1,
    },
    DemoAtom {
        id: "pinned-2",
        title: "Pinned atom drag reorder",
        project_key: "opencore",
        project_title: "opencore_rustroops",
        branch: Some("feat/left-sidebar"),
        shelf: AtomShelf::Pinned,
        time_label: "45m",
        status: AtomStatus::Ready,
        pr_number: None,
        diff_insertions: None,
        diff_deletions: None,
        is_unread: false,
        is_woke: false,
        terminal_process_count: 0,
    },
    DemoAtom {
        id: "active-1",
        title: "Implement left sidebar UI",
        project_key: "opencore",
        project_title: "opencore_rustroops",
        branch: Some("feat/left-sidebar"),
        shelf: AtomShelf::Active,
        time_label: "now",
        status: AtomStatus::Ready,
        pr_number: None,
        diff_insertions: None,
        diff_deletions: None,
        is_unread: false,
        is_woke: false,
        terminal_process_count: 0,
    },
    DemoAtom {
        id: "active-2",
        title: "Theme transition polish",
        project_key: "opencore",
        project_title: "opencore_rustroops",
        branch: Some("main"),
        shelf: AtomShelf::Active,
        time_label: "18m",
        status: AtomStatus::Monitoring,
        pr_number: None,
        diff_insertions: Some(12),
        diff_deletions: Some(3),
        is_unread: true,
        is_woke: false,
        terminal_process_count: 0,
    },
    DemoAtom {
        id: "active-3",
        title: "Approval gate on deploy",
        project_key: "sample_app",
        project_title: "sample_app",
        branch: Some("feat/deploy"),
        shelf: AtomShelf::Active,
        time_label: "45m",
        status: AtomStatus::Approval,
        pr_number: Some(17),
        diff_insertions: None,
        diff_deletions: None,
        is_unread: true,
        is_woke: false,
        terminal_process_count: 0,
    },
    DemoAtom {
        id: "active-4",
        title: "Review gpui-component dock APIs",
        project_key: "sample_app",
        project_title: "sample_app",
        branch: Some("research/dock"),
        shelf: AtomShelf::Active,
        time_label: "2h",
        status: AtomStatus::Ready,
        pr_number: None,
        diff_insertions: None,
        diff_deletions: None,
        is_unread: false,
        is_woke: false,
        terminal_process_count: 0,
    },
    DemoAtom {
        id: "settled-1",
        title: "Welcome view port",
        project_key: "opencore",
        project_title: "opencore_rustroops",
        branch: Some("main"),
        shelf: AtomShelf::Settled,
        time_label: "1d",
        status: AtomStatus::Ready,
        pr_number: Some(38),
        diff_insertions: None,
        diff_deletions: None,
        is_unread: false,
        is_woke: false,
        terminal_process_count: 0,
    },
    DemoAtom {
        id: "settled-2",
        title: "Shell workspace title bar",
        project_key: "opencore",
        project_title: "opencore_rustroops",
        branch: Some("feat/shell"),
        shelf: AtomShelf::Settled,
        time_label: "3d",
        status: AtomStatus::Ready,
        pr_number: None,
        diff_insertions: None,
        diff_deletions: None,
        is_unread: false,
        is_woke: false,
        terminal_process_count: 0,
    },
    DemoAtom {
        id: "settled-3",
        title: "Preferences persistence",
        project_key: "opencore",
        project_title: "opencore_rustroops",
        branch: None,
        shelf: AtomShelf::Settled,
        time_label: "1w",
        status: AtomStatus::Ready,
        pr_number: None,
        diff_insertions: None,
        diff_deletions: None,
        is_unread: false,
        is_woke: false,
        terminal_process_count: 0,
    },
    DemoAtom {
        id: "settled-4",
        title: "Dock animation tween",
        project_key: "opencore",
        project_title: "opencore_rustroops",
        branch: Some("feat/dock-tween"),
        shelf: AtomShelf::Settled,
        time_label: "2w",
        status: AtomStatus::Ready,
        pr_number: Some(12),
        diff_insertions: None,
        diff_deletions: None,
        is_unread: false,
        is_woke: false,
        terminal_process_count: 0,
    },
    DemoAtom {
        id: "settled-5",
        title: "Native menu bridge",
        project_key: "opencore",
        project_title: "opencore_rustroops",
        branch: Some("main"),
        shelf: AtomShelf::Settled,
        time_label: "2w",
        status: AtomStatus::Failed,
        pr_number: None,
        diff_insertions: None,
        diff_deletions: None,
        is_unread: false,
        is_woke: false,
        terminal_process_count: 0,
    },
    DemoAtom {
        id: "settled-6",
        title: "atom sidebar search",
        project_key: "sample_app",
        project_title: "sample_app",
        branch: Some("feat/search"),
        shelf: AtomShelf::Settled,
        time_label: "3w",
        status: AtomStatus::Woke,
        pr_number: None,
        diff_insertions: None,
        diff_deletions: None,
        is_unread: false,
        is_woke: true,
        terminal_process_count: 0,
    },
    DemoAtom {
        id: "settled-7",
        title: "Composer placeholder text",
        project_key: "opencore",
        project_title: "opencore_rustroops",
        branch: Some("main"),
        shelf: AtomShelf::Settled,
        time_label: "4w",
        status: AtomStatus::Ready,
        pr_number: None,
        diff_insertions: None,
        diff_deletions: None,
        is_unread: false,
        is_woke: false,
        terminal_process_count: 0,
    },
    DemoAtom {
        id: "settled-8",
        title: "Right panel file tree",
        project_key: "sample_app",
        project_title: "sample_app",
        branch: Some("feat/files"),
        shelf: AtomShelf::Settled,
        time_label: "5w",
        status: AtomStatus::Ready,
        pr_number: Some(9),
        diff_insertions: None,
        diff_deletions: None,
        is_unread: false,
        is_woke: false,
        terminal_process_count: 0,
    },
    DemoAtom {
        id: "settled-9",
        title: "Keyboard shortcut map",
        project_key: "opencore",
        project_title: "opencore_rustroops",
        branch: Some("main"),
        shelf: AtomShelf::Settled,
        time_label: "6w",
        status: AtomStatus::Input,
        pr_number: None,
        diff_insertions: None,
        diff_deletions: None,
        is_unread: false,
        is_woke: false,
        terminal_process_count: 0,
    },
];
